### ISSUE TITLE
Interface via ESPHome does not work with latest ESPHome release - 2025.11.0

### ISSUE THREAD

**Issue by HumanSkunk** [davesmeghead/visonic#221]
This integration has worked flawlessly for me for some time, and still does. However with the latest version of ESPHome 2025.11.0 the ESP8266 board I have connected to the serial interface is no longer able to compile.

I amended a copy of the yaml you provided in the wiki but there seems to be errors now with the Stream Server functionality used.

```
In file included from src/esphome/core/component.h:8,
                 from src/esphome/components/stream_server/stream_server.h:3,
                 from src/esphome/components/stream_server/stream_server.cpp:1:
src/esphome/components/stream_server/stream_server.cpp: In member function 'virtual void StreamServerComponent::dump_config()':
src/esphome/components/stream_server/stream_server.cpp:46:80: error: request for member 'c_str' in 'esphome::network::get_use_address()', which is of non-class type 'const char*'
   46 |     ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address().c_str(), this->port_);
      |                                                                                ^~~~~
src/esphome/core/log.h:101:101: note: in definition of macro 'esph_log_config'
  101 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/stream_server/stream_server.cpp:46:5: note: in expansion of macro 'ESP_LOGCONFIG'
   46 |     ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address().c_str(), this->port_);
      |     ^~~~~~~~~~~~~
Compiling .pioenvs/alarm-interface/src/esphome/core/component.cpp.o
*** [.pioenvs/alarm-interface/src/esphome/components/stream_server/stream_server.cpp.o] Error 1
========================== [FAILED] Took 7.10 seconds ==========================

```

I have not encountered this issue before but perhaps with the new version of ESPHome it uses this function differently? It still works fine with the previous build version so for now everything is fine. Just wondered if this issue has been seen elsewhere or whether you are able to replicate it and recommend a fix?

I have pasted my config below, removed the sensitive bits:

```
esphome:
  name: alarm-interface
  friendly_name: Alarm Interface

esp8266:
  board: esp01_1m

external_components:
#  - source: github://thegroove/esphome-serial-server
  - source: github://oxan/esphome-stream-server
#  - source: github://joshuaspence/esphome-stream-server

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0   # disables logging to the serial UART (as we are using it for other things)

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP Fallback Hotspot"
    password: !secret ap_password

  manual_ip:
    static_ip: !secret network_ip
    gateway: !secret network_gateway
    subnet: !secret network_mask

captive_portal:

button:
  # Switch to restart the plug
  - platform: restart
    name: "Panel Interface Restart"

uart:
  id: uart_bus_visonic
  baud_rate: !secret panel_baud_rate
  tx_pin: 1
  rx_pin: 3
  stop_bits: 1
  data_bits: 8
  parity: NONE

stream_server:
#serial_server:
  id: my_stream
  uart_id: uart_bus_visonic
  port: 10077

**Comment by HumanSkunk** [comment]
After trying to solve this and finally giving in and submitting the ticket I checked the https://github.com/oxan/esphome-stream-server repo page and noticed a fix was pushed 4 hours ago. Realised that ESPHome was caching the stream server repo and a single line entry to force a refresh each time I compile it solved it.

Now working fine.

For anyone else having this issue just replace with this.

```
external_components:
  - source: github://oxan/esphome-stream-server
    refresh: 0s
```

Just make sure the refresh is at the same indent level.

I will leave this open so if anyone else encounters this today they can see this fix. Will close it in a week.
